
USE Konoha4k;

CREATE TABLE Ninjas(
id INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(255) NOT NULL,
Rango VARCHAR(255) NOT NULL,
Aldea VARCHAR(255) NOT NULL);

CREATE TABLE Misiones(
id INT AUTO_INCREMENT PRIMARY KEY,
Descripcion VARCHAR(255) NOT NULL,
Rango VARCHAR(255) NOT NULL,
Recompensa VARCHAR(255) NOT NULL);

CREATE TABLE MisionNinja(
id INT AUTO_INCREMENT PRIMARY KEY,
id_Ninja INT,
id_Mision INT,
FechaInicio DATE NOT NULL,
FechaFin DATE NOT NULL,
FOREIGN KEY(id_Ninja) REFERENCES Ninjas(id),
FOREIGN KEY(id_Mision) REFERENCES Misiones(id));

CREATE TABLE Jutsus(
id INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(255) NOT NULL,
Descripcion VARCHAR(255) NOT NULL);

CREATE TABLE RegistroJutsus(
id INT AUTO_INCREMENT PRIMARY KEY,
id_Jutsu INT,
id_Ninja INT,
FOREIGN KEY (id_Jutsu) REFERENCES Jutsus(id),
FOREIGN KEY (id_Ninja) REFERENCES Ninjas(id));
